
[gmail]
email = "mittapallilokeswarreddy10@gmail.com"
app_password = "YOUR_GMAIL_APP_PASSWORD"

[twilio]
account_sid = "YOUR_TWILIO_ACCOUNT_SID"
auth_token = "YOUR_TWILIO_AUTH_TOKEN"
from_number = "+1234567890"
