[gmail]
email = "mittapallilokeswarreddy10@gmail.com"
app_password = "dxla ypaw rlsx oumu"

[twilio]
account_sid = "US48914caaa4545107fd73bc7ca4151c0b"
auth_token = "YOUR_TWILIO_AUTH_TOKEN"
from_number = "+917013117053"
